on:
  workflow_call:
    outputs:
      artifact-name:
        description: "The name of the built artifact"
        value: ${{ jobs.build.outputs.artifact-name }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno install

      - name: Build
        run: deno task build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: artifact
          path: dist

      - name: Set workflow output
        id: set-output
        run: echo "artifact-name=artifact" >> $GITHUB_OUTPUT
