on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ !github.event.release.prerelease }}
    permissions:
      contents: read
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true
        
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tag/stable
          file: dist.zip

      - name: Unzip dist
        run: unzip -o ./dist.zip -d ./dist
      
      - name: Deploy
        run: deno task deploy
        env:
          PROJECT_ID: ${{ vars.PROJECT_NAME }}
          DEPLOY_TOKEN: ${{ secrets.PROJECT_TOKEN }}
