name: Semantic Release Dispatch

on:
  workflow_dispatch:

jobs:
  run-remantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    #   - name: Generate Token
    #     id: app-token
    #     uses: actions/create-github-app-token@v2
    #     with:
    #       app-id: ${{ secrets.BOT_APP_ID }}
    #       private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v5
        # with:
        #  fetch-depth: 0
        #  persist-credentials: false

      - uses: cycjimmy/semantic-release-action@v5
        with:
          dry_run: true
        env:
        #   GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
